### ISSUE TITLE
Please Remove MY IPTV Sub (willfonk links) or expect DMCA

### ISSUE THREAD

**Issue by AstaFatherSatan** [kusnadipepenk/ntn#1]
Please Remove my personal IPTV Sub (willfonk links) or expect DMCA

**Comment by kusnadipepenk** [comment]
Hello,
can you give an example of which link includes MY IPTV Sub (willfonk links)?
All existing IPTV links I got from Google search results and also from what others posted.

Sorry for the inconvenience.
Thank you

**Comment by AstaFatherSatan** [comment]
all of them. they contain my mac address which leaked from my older github repo before i made variables for them.

**Comment by AstaFatherSatan** [comment]
i can email a picture if you need of my mac address on the box

**Comment by kusnadipepenk** [comment]
All of them? 
Yes, Please give me an example link (Mac). I don't think that all channels (links) belong to MY IPTV Sub (willfonk links).
Thanks

**Comment by AstaFatherSatan** [comment]
lines #718-725 of[ eeee.m3u](https://github.com/kusnadipepenk/ntn/blob/master/eeeee.m3u)

**Comment by AstaFatherSatan** [comment]
&m=

**Comment by AstaFatherSatan** [comment]
&t is my token as well

**Comment by kusnadipepenk** [comment]
#EXTINF:-1 group-title="SPORTS",Jsport1
https://stream01.willfonk.com/live_playlist.m3u8?cid=BS242&r=HD&ccode=JP&m=d0:20:20:04:35:cc&t=0d6938cb3dcf4b79848bc1753a59daf1
#EXTINF:-1 group-title="SPORTS",Jsport2
https://stream01.willfonk.com/live_playlist.m3u8?cid=BS243&r=HD&ccode=JP&m=d0:20:20:04:35:cc&t=0d6938cb3dcf4b79848bc1753a59daf1
#EXTINF:-1 group-title="SPORTS",Jsport3
https://stream01.willfonk.com/live_playlist.m3u8?cid=BS244&r=HD&ccode=JP&m=d0:20:20:04:35:cc&t=0d6938cb3dcf4b79848bc1753a59daf1
#EXTINF:-1 group-title="SPORTS",Jsport4
https://stream01.willfonk.com/live_playlist.m3u8?cid=BS245&r=HD&ccode=JP&m=d0:20:20:04:35:cc&t=0d6938cb3dcf4b79848bc1753a59daf1

Only this, right?
Ok wait, I will delete this link.

**Comment by AstaFatherSatan** [comment]
yes those

**Comment by AstaFatherSatan** [comment]
thank you. also please delete the issue or make it private after so it doesnt happen more.
